[package]
name = "backtest"
version = "0.1.0"
authors = ["Abhisheak Mall <shakecross@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv  = "1.1.5"
serde = "1.0.118"
